### ISSUE TITLE
Incompatibility with Windows...

### ISSUE THREAD

**Issue by OrnitOnGithub** [AxaQuilPre/Games.Py#13]
README.md: `"This project is aimed to create custom minor 100% python based minigames easily executable`***`on any machine."`***

Wrong! I looked through the code and there is one main incompatibility:
example: game_hangman.py:10 : `dictionnary_path = "Libraries/Lib_Hangman/lib_dict_hangman.json"`

If you use strings for file paths (`"example_dir/example_file"`), UNIX machines (MacOS, Linux...) will require forward slash, but other systems like Windows require backward slashes. So in its current state game_hangman won't work on Windows.

This can be fixed in two ways:

```
import os

file_path = os.path.join("example_dir", "example_file")
```
or
```
from pathlib import Path

# Construct a platform-independent file path
file_path = Path("example_dir") / "example_file"
```

I recommend the first option as `os` is already part of the python built-in library and won't require a new dependency.

We can:
- Replace file path strings with the new solution and remember to use it in the future as well.
- Do this later.
- Fuck Windows.

You choose.

Also pls don't assign this issue to me Idfk how to work with y'all's code

**Comment by AxaQuilPre** [comment]
Fixed
