### ISSUE TITLE
Reorganise to follow conventions / make this repo readable

### ISSUE THREAD

**Issue by OrnitOnGithub** [AxaQuilPre/Games.Py#6]
These are all my suggestions:
- Put all code in a "src" folder.
- The readme is for:
    - How to install
    - How to play
    - Dependencies
- "Ideas" can go in another file or can be github issues.
- Follow python conventions and use snake_case ( currently you're using a mix of everything)
- For semantic version naming use "major"."minor"."hotfix" (i.e. ver. 0.1.1)
- Semantically name releases instead of the main python file (rename hangman-1.0.py to main.py and create a release called 0.1.0)

Also:
- You can create shell scripts to download all dependencies

**Comment by DrN1ghtW0lf** [comment]
We will take that into account, though you could fix Read-me, ideas and naming conventions right ?

**Comment by AxaQuilPre** [comment]
Dependencies are gonna be requirements.txt, but we can have a copy of it in the readme

**Comment by AxaQuilPre** [comment]
And no need for src since GitHub makes it for you when creating a release.
